apiVersion: apps/v1
kind: Deployment
metadata:
  name: qprofiles-deployment
  labels:
    app: qprofiles
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qprofiles
  template:
    metadata:
      labels:
        app: qprofiles
    spec:
      containers:
      - name: qprofiles
        image: qprofilesdemo/python:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: qprofiles-service
spec:
  type: NodePort
  selector:
    app: qprofiles
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
